# Generated by Django 5.1.4 on 2024-12-04 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='image',
            field=models.ImageField(upload_to='bouquets/'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
